import React from 'react'
import Footer from './Footer'

const Games = () => {
  return (
    <>
      <div className="gam_sec1">
       <div className="gam_sec1_img">
       <img src="https://www.gamedistrict.co/assets/img/left-icon.jpg"  alt="" />
            <img src="https://www.gamedistrict.co/assets/img/icon-g.jpg"  alt="" />
            <img src="https://www.gamedistrict.co/assets/img/right-icon.jpg"  alt="" />
       </div>
      </div>
       <div className="gam_sec2">
        
      </div>
      <div className="gam_sec3"   data-aos="zoom-in">
      <div className="gam_sec3_img">
        <img src="https://www.gamedistrict.co/assets/img/why-client-1.jpg" alt="" />
        <img src="https://www.gamedistrict.co/assets/img/why-client-2.jpg" alt="" />
        <img src="https://www.gamedistrict.co/assets/img/why-client-3.jpg" alt="" />
        <img src="https://www.gamedistrict.co/assets/img/why-client-4.jpg" alt="" />
        </div>
      </div>

      <div className="gam_sec4">
        <div className='gam_sec4_1' data-aos="slide-left">
            <h1>Create your next</h1>
            <h2>Viral Game<br/> App</h2>
            <p>85% of the top grossing apps are games. App Store growing at an unprecedented rate has made game development an opportunity of our decade. Turn your idea into reality and build the next viral mobile game.</p>
        </div>
        <div className='gam_sec4_2'  >
          <div className="gam_sec4_2_img">
           <img  src="https://www.gamedistrict.co/assets/img/game-icon-1.png" alt="" />
           <img src="https://www.gamedistrict.co/assets/img/game-icon-2.png" alt="" />
           <img src="https://www.gamedistrict.co/assets/img/game-icon-3.png" alt="" />
           <img src="https://www.gamedistrict.co/assets/img/game-icon-4.png" alt="" />
        </div>
        </div>
      </div>

      <div className="gam_sec5">
           <div className="gam_sec5_1" data-aos="zoom-in-left">
            <img src="https://www.gamedistrict.co/assets/img/era.jpg" alt="" />
           </div>
           <div className="gam_sec5_2" data-aos="slide-left">
            <h1>the era of</h1>
            <h3>Mobile Games</h3>
            <p>With 2 Billion smartphone users around the world, App Store & Google Play revenues are expected to reach tens of billions of dollars in the next couple of years. Clearly, mobile is taking over a big part of the entertainment business traditionally generated by PCs & games console.</p>
            <p>This makes game app development a tremendous opportunity in the consumer technology revolution we are experiencing now. Not surprisingly, game apps represent the majority of revenues out of developers.</p>
           </div>
      </div>

      <div className="gam_sec6">
        <div className="gam_sec6_1" data-aos="slide-right">
            <h1>the challenge of</h1>
            <h2>Delivering The Best</h2>
            <p>The rising numbers of mobile users & digital opinions has made game development a crucial & challenging task. But our team at Game District counters all the hurdles with professional approach & tactics.</p>
            <p>Separating the venture into Deisgn, Development & Publishing allows us to cater the various aspects of the game properly.
            </p>
        </div>
        <div className="gam_sec6_2" data-aos="slide-down">
            <img src="https://www.gamedistrict.co/assets/img/icon-user-acquisition.jpg" alt="" />
            <h3>User Acquisition</h3>
            <p>If your customer acquisition costs are too high, you may not be able to sustain your business. Most successful game apps, such as Candy Crush or QuizUp, have hacked their growth by implementing smart referral and viral features.</p>
        </div>
        <div className="gam_sec6_3"   data-aos="slide-left">
            <div className='gam_sec6_3_1'>
                <img src="https://www.gamedistrict.co/assets/img/icon-engagement.jpg" alt="" />
                <h3>Engagement</h3>
                <p>EngagementCryptocurrencies are no longer unregulated. Depending on their status and location, digital currency apps may have to comply with rules such as Anti-Money Laundering Programs, Suspicious Activity Reports etc</p>
            </div>
            <div className='gam_sec6_3_1'>
            <img src="https://www.gamedistrict.co/assets/img/icon-monetization.jpg" alt="" />
                <h3>Engagement</h3>
                <p>EngagementCryptocurrencies are no longer unregulated. Depending on their status and location, digital currency apps may have to comply with rules such as Anti-Money Laundering Programs, Suspicious Activity Reports etc</p>
            </div>
        </div>
      </div>
      <div className="gam_sec7" data-aos="slide-up">
        <h1>How can we help in</h1>
        <h2>Your Venture</h2>
        <p>n Game Development, achieving greatness is about turning your creative vision into a seamless and engaging player experience. That’s what makes a difference between awesomeness and mediocrity when it comes to engagement.</p>
        <p>However, your overall strategy should go way beyond development aspect. Although your product strategy should be about crafting an amazing user experience, it needs to think about implementing an effective monetization and business strategy.</p>
      </div>

      <div className="gam_sec8">
        <div className="gam_sec8_img">
        <img data-aos="slide-right" src="https://www.gamedistrict.co/assets/img/venture-icon-1.jpg" alt="" />
        <img data-aos="slide-down" src="https://www.gamedistrict.co/assets/img/venture-icon-2.jpg" alt="" />
        <img data-aos="slide-left" src="https://www.gamedistrict.co/assets/img/venture-icon-3.jpg" alt="" />
      </div>
      </div>

      <div className="gam_sec9">
        <div className="gam_sec9_1" data-aos="slide-right">
            <h1>It all starts with</h1>
            <h2>The Right Strategy</h2>
            <p>The quality of game design ultimately depends on creativty and vision. But that represents only part of the story. Tranforming this creative vision into an engaging and semaless user experience, while building a viable business model on top of it, is what separates mediocrity from greatness.</p>
            <p>At Game District, we undrestand this. Our product managers worked on a wide range of top selling game apps, which cumulatively achieved tens of millions of downloads.</p>
            <p>From fleshing out the initial creative idea, building an exciting storyboard and crafting an amazing user epxerience to building a viable monetization energy, our product manager will work with you on every aspect of your game</p>
        </div>
        <div className="gam_sec9_2" data-aos="slide-left">

        </div>
      </div>

      <div className="gam_sec10" data-aos="slide-down">
        <img src="https://www.gamedistrict.co/assets/img/inside.jpg" alt="" />
        <p>Game District longs for fresh & young minds who can mould their approaches with the changing challenges of the digital industry. A growing mind is one of the cherished sights for us as it’s a proof of growth & success in the right direction.</p>
      </div>

        <div className="gam_sec11">
            <img data-aos="slide-right" src="https://www.gamedistrict.co/assets/img/inside-g-1.jpg" alt="" />
            <img data-aos="slide-up" src="https://www.gamedistrict.co/assets/img/inside-g-2.jpg" alt="" />
            <img data-aos="slide-down" src="https://www.gamedistrict.co/assets/img/inside-g-3.jpg" alt="" />
            <img data-aos="zoom-out" src="https://www.gamedistrict.co/assets/img/inside-g-4.jpg" alt="" />
            <img data-aos="slide-left" src="https://www.gamedistrict.co/assets/img/inside-g-5.jpg" alt="" />
        </div>
        <div className="gam_sec11">
            <img data-aos="slide-right" src="https://www.gamedistrict.co/assets/img/inside-g-6.jpg" alt="" />
            <img data-aos="slide-down" src="https://www.gamedistrict.co/assets/img/inside-g-7.jpg" alt="" />
            <img data-aos="slide-up" src="https://www.gamedistrict.co/assets/img/inside-g-8.jpg" alt="" />
            <img data-aos="slide-left" src="https://www.gamedistrict.co/assets/img/inside-g-9.jpg" alt="" />
            <img data-aos="slide-left" src="https://www.gamedistrict.co/assets/img/inside-g-10.jpg" alt="" />
        </div>

        <div className="gam_sec12" >
            <button data-aos="slide-up">APPLY NOW</button>
        </div>
        <Footer/>
    </>
  )
}

export default Games
